export const DIGITAL_GOOD_SHOP = 'Digital Goods Shop'
export const PHYSICAL_GOODS_SHOP = 'Physical Goods Shop'
export const WEBSITE = 'Website'
export const CHARITY = 'Charity'
export const NFT_ART = 'ART NFT'
export const UNATTACHED_DOMAIN_NAME = 'Unattached Domain Name'
